const reyes = [
    {
        nombre: "Atanagildo",
        reinado: 15,
        vacasComidas: 9,
        color: "darkolivegreen",
        precio: 178,
        imagen: "https://www.html6.es/img/rey_atanagildo.png",
    },
    {
        nombre: "Ervigio",
        reinado: 7,
        vacasComidas: 3,
        color: "crimson",
        precio: 169,
        imagen: "https://www.html6.es/img/rey_ervigio.png",
    },
    {
        nombre: "Ataúlfo",
        reinado: 5,
        vacasComidas: 16,
        color: "peru",
        precio: 81,
        imagen: "https://www.html6.es/img/rey_ataulfo.png",
    },
    {
        nombre: "Leovigildo",
        reinado: 18,
        vacasComidas: 3,
        color: "darkmagenta",
        precio: 126,
        imagen: "https://www.html6.es/img/rey_leogivildo.png",
    },
    {
        nombre: "Sisebuto",
        reinado: 9,
        vacasComidas: 13,
        color: "teal",
        precio: 69,
        imagen: "https://www.html6.es/img/rey_sisebuto.png",
    },
    {
        nombre: "Recesvinto",
        reinado: 19,
        vacasComidas: 11,
        color: "royalblue",
        precio: 141,
        imagen: "https://www.html6.es/img/rey_recesvinto.png",
    },
    {
        nombre: "Teodorico",
        reinado: 33,
        vacasComidas: 12,
        color: "yellowgreen",
        precio: 89,
        imagen: "https://www.html6.es/img/rey_teodorico.png",
    },
];
export default reyes;
